# Generated by Django 3.2 on 2021-04-23 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EducationGroup',
            fields=[
                ('code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('en_year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('tcode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('employee_post', models.CharField(max_length=20)),
                ('academic_degree', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('gender', models.CharField(choices=[('m', 'Мужчина'), ('f', 'Женщина')], max_length=1)),
                ('department_s', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.departments')),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('stud_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(max_length=20)),
                ('entry_year', models.CharField(max_length=4)),
                ('email', models.EmailField(max_length=50)),
                ('gender', models.CharField(choices=[('m', 'Мужчина'), ('f', 'Женщина')], max_length=1)),
                ('edu_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.educationgroup')),
                ('facultys', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.faculty')),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('speciality_name', models.CharField(max_length=60)),
                ('faculty_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='educationgroup',
            name='speciality_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.speciality'),
        ),
        migrations.AddField(
            model_name='departments',
            name='faculty_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.faculty'),
        ),
    ]
