# Generated by Django 3.1.2 on 2021-05-04 19:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20210425_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='teachers',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subname', models.CharField(max_length=100)),
                ('subfrom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Paperwork',
            fields=[
                ('code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('score', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('deadline', models.DateTimeField()),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.subjects')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.teachers')),
            ],
        ),
    ]
