# Generated by Django 3.1.2 on 2021-05-04 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_auto_20210504_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperwork',
            name='score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='paperwork',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
