# Generated by Django 3.1.2 on 2021-05-04 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_auto_20210504_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperwork',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.students'),
        ),
    ]
