# Generated by Django 3.1.2 on 2021-05-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_paperwork_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='allow_depart',
            field=models.ManyToManyField(to='education.Departments'),
        ),
    ]
