# Generated by Django 3.1.2 on 2021-05-07 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.paperwork'),
        ),
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('-1', 'Отклонена'), ('0', 'Принята'), ('1', 'Рассматривается')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
