# Generated by Django 3.1.2 on 2021-05-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_auto_20210507_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('-1', 'Отклонена'), ('0', 'Принята'), ('1', 'Занята'), ('2', 'Рассматривается')], max_length=2),
        ),
        migrations.AddField(
            model_name='students',
            name='s_tag',
            field=models.ManyToManyField(blank=True, to='education.Tag'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='t_tag',
            field=models.ManyToManyField(blank=True, to='education.Tag'),
        ),
    ]
